### App Version Endpoints
POST http://localhost:3000/app-version/
Content-Type: application/json
{
  "component": "frontend",
  "major": 1,
  "minor": 0,
  "patch": 0
}

GET http://localhost:3000/app-version/frontend
Content-Type: application/json

PUT http://localhost:3000/app-version/frontend
Content-Type: application/json

{
  "patch": 1
}


### Notes Endpoints

# List all notes
GET http://localhost:3000/notes
Accept: application/json
Cookie: access_token={{accessToken}}

###

# Read a specific note by ID
GET http://localhost:3000/notes/{{noteId}}
Accept: application/json
Cookie: access_token={{accessToken}}

###

# Create a new note
POST http://localhost:3000/notes
Content-Type: application/json
Cookie: access_token={{accessToken}}

{
  "title": "Sample Note 2",
  "content": "This is a sample markdown **note** \n# By user Bon Flock!.",
  "isPinned": false
}

###

# Update a note by ID
PUT http://localhost:3000/notes/{{noteId}}
Content-Type: application/json
Cookie: access_token={{accessToken}}

{
  "title": "Sample Note",
  "content": "This is a sample markdown **note** \n# Heading one!.\n## Heading two!.",
  "isPinned": true
}

###

# Pin a note by ID
PATCH http://localhost:3000/notes/{{noteId}}/pin
Content-Type: application/json
Cookie: access_token={{accessToken}}

{
  "isPinned": false
}

###

# Delete a note by ID
DELETE http://localhost:3000/notes/{{noteId}}
Accept: application/json
Cookie: access_token={{accessToken}}

###

### Users Endpoints

# List all users
GET http://localhost:3000/users
Accept: application/json
Cookie: access_token={{accessToken}}

###

# Get a specific user by ID
GET http://localhost:3000/users/{{userId}}
Accept: application/json
Cookie: access_token={{accessToken}}

###

# Create a new user
POST http://localhost:3000/users
Content-Type: application/json
Cookie: access_token={{accessToken}}

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "password": "Password123!"
}

###

# Update a user by ID
PATCH http://localhost:3000/users/{{userId}}
Content-Type: application/json
Cookie: access_token={{accessToken}}

{
  "firstName": "Don",
  "lastName": "Rock"
}

###

# Delete a user by ID
DELETE http://localhost:3000/users/{{userId}}
Accept: application/json
Cookie: access_token={{accessToken}}

###

### Auth Endpoints

# Register a new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "firstName": "Bon",
  "lastName": "Flock",
  "email": "bonflock@gmail.com",
  "password": "qwER12#$",
  "confirmPassword": "qwER12#$"
}

###

# Login a user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "bonflock@gmail.com",
  "password": "qwER12#$"
}

###

# Get authenticated user
GET http://localhost:3000/auth
Accept: application/json
Cookie: access_token={{accessToken}}

###

# Sign out user
POST http://localhost:3000/auth/signout
Accept: application/json
Cookie: access_token={{accessToken}}

###

### Groups Endpoints

# Create a new group
POST http://localhost:3000/groups
Content-Type: application/json
Cookie: access_token={{accessToken}}

{
  "name": "New Group"
}

###

# Add a user to a group
POST http://localhost:3000/groups/{{groupId}}/users
Content-Type: application/json
Cookie: access_token={{accessToken}}

{
  "email": "user@example.com"
}

###

# Assign a folder to a group
POST http://localhost:3000/groups/{{groupId}}/folders
Content-Type: application/json
Cookie: access_token={{accessToken}}

{
  "folderId": "{{folderId}}"
}

###

### Folders Endpoints

# Create a new folder
POST http://localhost:3000/folders
Content-Type: application/json
Cookie: access_token={{accessToken}}

{
  "name": "New Folder",
  "description": "Folder description"
}

###

# List all folders
GET http://localhost:3000/folders
Accept: application/json
Cookie: access_token={{accessToken}}

###

# Get a folder by ID
GET http://localhost:3000/folders/{{folderId}}
Accept: application/json
Cookie: access_token={{accessToken}}

###

# Update a folder by ID
PATCH http://localhost:3000/folders/{{folderId}}
Content-Type: application/json
Cookie: access_token={{accessToken}}

{
  "name": "Updated Folder Name",
  "description": "Updated description"
}

###

# Delete a folder by ID
DELETE http://localhost:3000/folders/{{folderId}}
Accept: application/json
Cookie: access_token={{accessToken}}

###

# Share a folder
POST http://localhost:3000/folders/{{folderId}}/share
Content-Type: application/json
Cookie: access_token={{accessToken}}

{
  "userId": "{{userId}}",
  "permissions": [1, 2, 3]  // Replace with actual permission enums
}

###

### Folder Permissions Endpoints

# Update permissions for a folder
PATCH http://localhost:3000/folder-permissions/{{permissionId}}
Content-Type: application/json
Cookie: access_token={{accessToken}}

{
  "permissions": [1, 2, 3]  // Replace with actual permission enums
}

###

# Delete folder permissions
DELETE http://localhost:3000/folder-permissions/{{permissionId}}
Accept: application/json
Cookie: access_token={{accessToken}}

###