### Notes Endpoints

# List all notes
GET http://localhost:3000/notes
Accept: application/json

###

# List all notes by user ID
GET http://localhost:3000/notes/user/737549bd-3f87-496a-9e1e-89101fb76d96
Accept: application/json

###

# Read a specific note by ID
GET http://localhost:3000/notes/{{noteId}}
Accept: application/json

###

# Create a new note
POST http://localhost:3000/notes
Content-Type: application/json

{
  "title": "Sample Note 2",
  "content": "This is a sample markdown **note** \n# By user Bon Flock!.",
  "userId": "fa8418f7-095f-4ef6-b8c6-6aee17513e63",
  "isPinned": false
}

###

# Update a note by ID
PUT http://localhost:3000/notes/566a4c6d-5fa0-4aa2-afc3-ce533bdb9f4e
Content-Type: application/json

{
  "title": "Sample Note",
  "content": "This is a sample markdown **note** \n# Heading one!.\n## Heading two!.",
  "isPinned": true
}

###

# Pin a note by ID
PATCH http://localhost:3000/notes/566a4c6d-5fa0-4aa2-afc3-ce533bdb9f4e/pin
Content-Type: application/json

{
  "isPinned": false
}

###

# Delete a note by ID
DELETE http://localhost:3000/notes/{{noteId}}
Accept: application/json

###

### Users Endpoints

# List all users
GET http://localhost:3000/users
Accept: application/json

###

# Get a specific user by ID
GET http://localhost:3000/users/737549bd-3f87-496a-9e1e-89101fb76d96
Accept: application/json

###

# Create a new user
POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "password": "Password123!"
}

###

# Update a user by ID
PATCH http://localhost:3000/users/737549bd-3f87-496a-9e1e-89101fb76d96
Content-Type: application/json

{
  "firstName": "Don",
  "lastName": "Rock"
}

###

# Delete a user by ID
DELETE http://localhost:3000/users/{{userId}}
Accept: application/json

###

### Auth Endpoints

# Register a new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "firstName": "Bon",
  "lastName": "Flock",
  "email": "bonflock@gmail.com",
  "password": "qwER12#$",
  "confirmPassword": "qwER12#$"
}

// {
//   "firstName": "Don",
//   "lastName": "Rock",
//   "email": "donrockguitar@gmail.com",
//   "password": "qwER12#$",
//   "confirmPassword": "qwER12#$"
// }

###

# Login a user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "bonflock@gmail.com",
  "password": "qwER12#$"
}

// {
//   "email": "donrockguitar@gmail.com",
//   "password": "qwER12#$"
// }

###

# Get authenticated user
GET http://localhost:3000/auth
Accept: application/json
Cookie: access_token={{accessToken}}

###

# Sign out user
POST http://localhost:3000/auth/signout
Accept: application/json
Cookie: access_token={{accessToken}}